services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000"
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
    restart: always
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=memory_game
      - DATABASE_USER=memory_user
      - DATABASE_PASSWORD=memory_pass

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    networks:
      - app-network

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: memory_user
      POSTGRES_PASSWORD: memory_pass
      POSTGRES_DB: memory_game
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U memory_user -d memory_game"]
      interval: 5s  # Częstsze sprawdzanie stanu
      timeout: 5s   # Czas na odpowiedź
      retries: 10   # Więcej prób
      start_period: 15s  # Początkowy czas na pełne uruchomienie

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
