version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - game-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    networks:
      - game-network

networks:
  game-network:
    driver: bridge
